<?php
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PublicationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('publications')->delete();
        DB::table('publications')->insert([
            [
                'id' => 1,
                'title' => 'A BPMN-based language for modeling corporate communications',
                'year' => 2019,
                'journal' => 'Computer Standards & Interfaces',
                'url' => 'https://doi.org/10.1016/j.csi.2019.02.001',
                'authors' => 'Gregor Polančič, Boštjan Orban',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '1',
            ],
            [
                'id' => 2,
                'title' => 'A BPMN Extension for Business Process Outsourcing to the Cloud',
                'year' => 2019,
                'journal' => 'New Knowledge in Information Systems and Technologies (WorldCIST 19 2019)',
                'url' => 'https://link.springer.com/chapter/10.1007/978-3-030-16181-1_78',
                'authors' => 'Zarour, Karim and Benmerzoug, Djamel and Guermouche, Nawal and Drira, Khalil',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '2',
            ],
            [
                'id' => 3,
                'title' => 'A BPMN extension to model inter-organizational processes in industry 4.0',
                'year' => 2021,
                'journal' => 'Sensors',
                'url' => 'https://doi.org/10.3390/s23031456',
                'authors' => 'Vítor Ribeiro, João Barata, Paulo Rupino da Cunha',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '3',
            ],
            [
                'id' => 4,
                'title' => 'A Business Process and Data Modelling Approach to Enhance Cyber Security in Smart Cities',
                'year' => 2023,
                'journal' => 'International Journal of Advanced Computer Science and Applications (IJACSA)',
                'url' => 'https://link.springer.com/chapter/10.1007/978-3-031-59462-5_5',
                'authors' => 'Josef Horalek, Tereza Otcenaskova, Vladimir Sobeslav, Petr Tucnik',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '4',
            ],
            [
                'id' => 5,
                'title' => 'A Business Process Modeling Notation Extension for Real Time Handling-Application to Novel Coronavirus (2019-nCoV) management process',
                'year' => 2020,
                'journal' => 'Journal of Systems and Software',
                'url' => 'https://ieeexplore.ieee.org/abstract/document/9365900/',
                'authors' => 'Ouarhim, Asma and Lakhrouit, Jihane and Baïna, Karim',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '5',
            ],
            [
                'id' => 6,
                'title' => 'A Family of Experiments to generate Graphical User Interfaces from BPMN Models with Stereotypes',
                'year' => 2021,
                'journal' => 'Software and Systems Modeling',
                'url' => 'https://www.sciencedirect.com/science/article/pii/S0164121220302739',
                'authors' => 'Eduardo Díaz, José Ignacio Panach, Silvia Rueda, Damiano Distante',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '6',
            ],
            [
                'id' => 7,
                'title' => 'A Lightweight BPMN Extension for Business Process-Oriented Requirements Engineering',
                'year' => 2021,
                'journal' => 'Journal of Biomedical Informatics',
                'url' => 'https://www.mdpi.com/2073-431X/10/12/171',
                'authors' => 'Intrigila, Benedetto and Della Penna, Giuseppe and D’ambrogio, Andrea',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '7',
            ],
            [
                'id' => 8,
                'title' => 'A Migration Framework for Active BPMN Processes in Healthcare',
                'year' => 2024,
                'journal' => 'IEEE Access',
                'url' => 'https://ieeexplore.ieee.org/abstract/document/10628905/',
                'authors' => 'Matteo Mantovani, Emanuele Chini, Carlo Combi',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '8',
            ],
            [
                'id' => 9,
                'title' => 'A Model Based Framework for IoT-Aware Business Process Management',
                'year' => 2023,
                'journal' => 'International Journal of Information Management',
                'url' => 'https://www.mdpi.com/1999-5903/15/2/50',
                'authors' => 'Bocciarelli, Paolo and DAmbrogio, Andrea and Panetti, Tommaso',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '9',
            ],
            [
                'id' => 10,
                'title' => 'A Multi-criteria Evaluation Approach for Selecting a Sensitive Business Process Modeling Language for Knowledge Management',
                'year' => 2019,
                'journal' => 'International Journal of Information Management',
                'url' => 'https://link.springer.com/article/10.1007/s13740-019-00103-5',
                'authors' => 'Ben Hassen, Mariam and Turki, Mohamed and Gargouri, Faiez',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '10',
            ],
            [
                'id' => 11,
                'title' => 'A Performance Measurement Extension for BPMN: One Step Further Quantifying Interoperability in Process Model',
                'year' => 2019,
                'journal' => 'IFAC-PapersOnLine',
                'url' => 'https://link.springer.com/chapter/10.1007/978-3-030-13693-2_28',
                'authors' => 'Heguy, Xabier and Zacharewicz, Gregory and Ducq, Yves and Tazi, Said and Vallespir, Bruno',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '11',
            ],
            [
                'id' => 12,
                'title' => 'A variability-enabling and model-driven approach to adaptive microservice-based systems',
                'year' => 2021,
                'journal' => 'Journal of Systems and Software',
                'url' => 'https://ieeexplore.ieee.org/abstract/document/9529482/',
                'authors' => 'Sun, Chang-Ai and Wang, Jing and Liu, Zhenxian and Han, Yanbo',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '12',
            ],
            [
                'id' => 13,
                'title' => 'Analysis of the Runtime Resource Provisioning of BPMN Processes using Maude',
                'year' => 2020,
                'journal' => 'Software and Systems Modeling',
                'url' => 'https://link.springer.com/chapter/10.1007/978-3-030-63595-4_3',
                'authors' => 'Duran, Francisco and Rocha, Camilo and Salaun, Gwen',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '13',
            ],
            [
                'id' => 14,
                'title' => 'BPMN Extension for Multi-Protocol Data Orchestration',
                'year' => 2022,
                'journal' => 'IEEE Access',
                'url' => 'https://link.springer.com/chapter/10.1007/978-3-030-93547-4_28',
                'authors' => 'Chis, Andrei and Ghiran, Ana-Maria',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Book Chapter',
                'short_title' => '14',
            ],
            [
                'id' => 15,
                'title' => 'BPMN Extensions and Semantic Annotation in Public Administration Service Design',
                'year' => 2020,
                'journal' => 'Information Systems',
                'url' => 'https://link.springer.com/chapter/10.1007/978-3-030-64266-2_7',
                'authors' => 'Ardito, Carmelo and Caivano, Danilo and Colizzi, Lucio and Verardi, Loredana',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '15',
            ],
            [
                'id' => 16,
                'title' => 'BPMN Extensions for Modeling Continuous Processes',
                'year' => 2021,
                'journal' => 'Business Process Management Journal',
                'url' => 'https://link.springer.com/chapter/10.1007/978-3-030-79108-7_3',
                'authors' => 'Strutzenberger, Diana Viktoria and Mangler, Juergen and Rinderle-Ma, Stefanie',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '16',
            ],
            [
                'id' => 17,
                'title' => 'BPMN-E 2 : a BPMN extension for an enhanced workFlowElements description',
                'year' => 2019,
                'journal' => 'Journal of Universal Computer Science',
                'url' => 'https://link.springer.com/article/10.1007/s10270-018-0669-2',
                'authors' => 'Mateo Ramos-Merino, Juan M. Santos-Gago, Luis M. Álvarez-Sabucedo, Victor M. Alonso-Roris, Javier Sanz-Valero',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '17',
            ],
            [
                'id' => 18,
                'title' => 'BPMN-L: A BPMN extension for modeling of process landscapes',
                'year' => 2020,
                'journal' => 'Business Process Management Journal',
                'url' => 'https://www.sciencedirect.com/science/article/pii/S0166361520305108',
                'authors' => 'Gregor Polančič',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '18',
            ],
            [
                'id' => 19,
                'title' => 'BPMN++: Comprehensive Business Process Modeling for Industrial Internet Application',
                'year' => 2022,
                'journal' => 'IEEE Access',
                'url' => 'https://ieeexplore.ieee.org/abstract/document/10070662/',
                'authors' => 'Cheng, Hangyu and Kang, Guosheng and Liu, Jianxun and Wen, Yiping and Cao, Buqing and Wang, Zhen',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '19',
            ],
            [
                'id' => 20,
                'title' => 'BPMN+I to support decision making in innovation management for automated',
                'year' => 2020,
                'journal' => 'Procedia CIRP',
                'url' => 'https://www.sciencedirect.com/science/article/pii/S2405896320335904',
                'authors' => 'Birgit Vogel-Heuser, Felix Brodbeck, Katharina Kugler, Jan Passoth, Sabine Maasen, Julia Reif',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '20',
            ],
            [
                'id' => 21,
                'title' => 'BPMN4MOOC: a BPMN Extension for the Design of Connectivist MOOC',
                'year' => 2023,
                'journal' => 'Education and Information Technologies',
                'url' => 'https://www.tandfonline.com/doi/abs/10.1080/10494820.2023.2190353',
                'authors' => 'Bakki, Aïcha and Oubahssi, Lahcen and Laghouaouta, Youness and George, Sébastien',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '21',
            ],
            [
                'id' => 22,
                'title' => 'BPMN4SBP for Multi-dimensional Modeling of Sensitive Business Processes',
                'year' => 2022,
                'journal' => 'Information Systems',
                'url' => 'https://link.springer.com/chapter/10.1007/978-3-031-10983-6_49',
                'authors' => 'Ben Hassen, Mariam and Turki, Mohamed and Gargouri, Faiez',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '22',
            ],
            [
                'id' => 23,
                'title' => 'BPMN4sML: A BPMN Extension for Serverless Machine Learning',
                'year' => 2022,
                'journal' => 'IEEE Access',
                'url' => 'https://arxiv.org/abs/2208.02030',
                'authors' => 'Tetzlaff, Laurens Martin',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '23',
            ],
            [
                'id' => 24,
                'title' => 'BPMNE4IoT: A Framework for Modeling, Executing and Monitoring IoT-Driven Processes',
                'year' => 2023,
                'journal' => 'Sensors',
                'url' => 'https://www.mdpi.com/1999-5903/15/3/90',
                'authors' => 'Yusuf Kirikkayis, Florian Gallik, Michael Winter, Manfred Reichert',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '24',
            ],
            [
                'id' => 25,
                'title' => 'Business Process Improvement in Industry 4.0- An Interorganizational Perspective',
                'year' => 2021,
                'journal' => 'Journal of Industrial Information Integration',
                'url' => 'https://link.springer.com/chapter/10.1007/978-3-030-94343-1_22',
                'authors' => 'Vítor Hugo Ribeiro, João Barata and Paulo Rupino Cunha',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '25',
            ],
            [
                'id' => 26,
                'title' => 'Business Process Model and Notation for Forensic-Ready Software Systems',
                'year' => 2022,
                'journal' => 'Information and Software Technology',
                'url' => 'https://www.semanticscholar.org/paper/Business-Process-Model-and-Notation-for-Software-Daubner-Matulevi%C4%8Dius/4274999d60d0b469bf750536ec0bedb7bb43e20f',
                'authors' => 'Lukas Daubner, Raimundas Matulevicius, Barbora Buhnova and Tomas Pitner',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '26',
            ],
            [
                'id' => 27,
                'title' => 'Business process modeling extension and scheduling strategy compatible with big data business',
                'year' => 2023,
                'journal' => 'IEEE Access',
                'url' => 'https://ieeexplore.ieee.org/abstract/document/10141025/',
                'authors' => 'Jindong Xu, Minghao Qi',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '27',
            ],
            [
                'id' => 28,
                'title' => 'Business Process Modeling for Industrial Internet Application via BPMN Extension',
                'year' => 2024,
                'journal' => 'IEEE Access',
                'url' => 'https://ieeexplore.ieee.org/abstract/document/10483056/',
                'authors' => 'Guosheng Kang, Hangyu Cheng, Jianxun Liu, Yiping Wen, Jun Peng',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '28',
            ],
            [
                'id' => 29,
                'title' => 'Business Processes Meet Spatial Concerns: the sBPMN Verification Framework',
                'year' => 2021,
                'journal' => 'Information Systems',
                'url' => 'https://link.springer.com/chapter/10.1007/978-3-030-90870-6_12',
                'authors' => 'Saddem-Yagoubi, Rim and Poizat, Pascal and Houhou, Sara',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '29',
            ],
            [
                'id' => 30,
                'title' => 'Combined Use of PBMN and Rewriting Logic for Specification and Analysis of IoT Applications',
                'year' => 2022,
                'journal' => 'Journal of Systems and Software',
                'url' => 'https://link.springer.com/chapter/10.1007/978-3-031-18516-8_5',
                'authors' => 'Abbas, Sofia and Kerkouche, El Hillali and Khalfaoui, Khaled and Chaoui, Allaoua',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '30',
            ],
            [
                'id' => 31,
                'title' => 'Contributions for risk assessment of IoT-aware business processes at different granularity levels',
                'year' => 2021,
                'journal' => 'Journal of Industrial Information Integration',
                'url' => 'https://www.sciencedirect.com/science/article/pii/S1877050921015908',
                'authors' => 'Pedro Bandeiras Cardoso, Dulce Domingos, Ana Respício',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '31',
            ],
            [
                'id' => 32,
                'title' => 'Controllability of Business Processes with Temporal Variables',
                'year' => 2019,
                'journal' => 'Business Process Management Journal',
                'url' => 'https://dl.acm.org/doi/abs/10.1145/3297280.3297286',
                'authors' => 'Eder, Johann and Franceschetti, Marco and Kopke, Julius',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '32',
            ],
            [
                'id' => 33,
                'title' => 'Designing secure business processes for blockchains with SecBPMN2BC',
                'year' => 2023,
                'journal' => 'Information Systems',
                'url' => 'https://www.sciencedirect.com/science/article/pii/S0167739X22003764',
                'authors' => 'Julius Köpke and Giovanni Meroni and Mattia Salnitri',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '33',
            ],
            [
                'id' => 34,
                'title' => 'Dynamic Resource Allocation for Executable BPMN Processes Leveraging Predictive Analytics',
                'year' => 2024,
                'journal' => 'IEEE Access',
                'url' => 'https://ieeexplore.ieee.org/abstract/document/10684659/',
                'authors' => 'Yliès Falcone, Gwen Salaün, Ahang Zuo',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '34',
            ],
            [
                'id' => 35,
                'title' => 'Evaluating BPMN Extensions for Continuous Processes Based on Use Cases and Expert Interviews',
                'year' => 2024,
                'journal' => 'Business Process Management Journal',
                'url' => 'https://link.springer.com/article/10.1007/s12599-023-00850-7',
                'authors' => 'Diana Strutzenberger, Juergen Mangler, Stefanie Rinderle',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '35',
            ],
            [
                'id' => 36,
                'title' => 'Extending BPM(N) to Support Face-to-Virtual (F2V) Process Modeling',
                'year' => 2021,
                'journal' => 'Journal of Systems and Software',
                'url' => 'https://www.scitepress.org/PublishedPapers/2021/103492/103492.pdf',
                'authors' => 'Rudan, Sasha Mile and Rudan, Sinisa and Moller-Pedersen, Birger',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '36',
            ],
            [
                'id' => 37,
                'title' => 'Extending BPMN 2.0 for intraoperative workFlowElements modeling with IEEE 11073 SDC for description and orchestration of interoperable, networked medical devices',
                'year' => 2019,
                'journal' => 'Journal of Biomedical Informatics',
                'url' => 'https://www.scitepress.org/PublishedPapers/2021/103492/103492.pdf',
                'authors' => 'Juliane Neumann, Stefan Franke, Max Rockstroh, Martin Kasparick, Thomas Neumuth',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '37',
            ],
            [
                'id' => 38,
                'title' => 'Extending BPMN Models with Sensitive Business Process Aspects',
                'year' => 2022,
                'journal' => 'Information Systems',
                'url' => 'https://www.sciencedirect.com/science/article/pii/S1877050922012443',
                'authors' => 'Mariam Ben Hassen and Mohamed Turki and Faïez Gargouri',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '38',
            ],
            [
                'id' => 39,
                'title' => 'Extension of the Functional Dimension of BPMN Based on MDA Approach for Sensitive Business Processes Execution',
                'year' => 2024,
                'journal' => 'Software and Systems Modeling',
                'url' => 'https://link.springer.com/chapter/10.1007/978-3-031-51664-1_17',
                'authors' => 'Zohra Alyani, Mohamed Turki, Faiez Gargouri',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '39',
            ],
            [
                'id' => 40,
                'title' => 'Forensic-Ready Analysis Suite: A Tool Support for Forensic-Ready Software Systems Design',
                'year' => 2024,
                'journal' => 'Information and Software Technology',
                'url' => 'https://link.springer.com/chapter/10.1007/978-3-031-59468-7_6',
                'authors' => 'Lukas Daubner, Sofija Maksović, Raimundas Matulevičius, Barbora Buhnova, Tomás̆ Sedlác̆ek',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '40',
            ],
            [
                'id' => 41,
                'title' => 'From Static to Dynamic Analysis and Allocation of Resources for BPMN Processes',
                'year' => 2022,
                'journal' => 'IEEE Access',
                'url' => 'https://link.springer.com/chapter/10.1007/978-3-031-12441-9_1',
                'authors' => 'Duran, Francisco and Falcone, Ylies and Rocha, Camilo and Salaun, Gwen and Zuo, Ahang',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '41',
            ],
            [
                'id' => 42,
                'title' => 'Graphical Specification of Sensitive Business Processes',
                'year' => 2024,
                'journal' => 'Journal of Systems and Software',
                'url' => 'https://www.sciencedirect.com/science/article/pii/S1877050924011001',
                'authors' => 'Mariam Ben Hassen, Faïez Gargouri',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => 9,
                'type' => 'Journal',
                'short_title' => '42',
            ],
            [
                'id' => 43,
                'title' => 'How to manage and model unstructured business processes- A proposed list of representational requirements',
                'year' => 2019,
                'journal' => 'Business Process Management Journal',
                'url' => 'https://link.springer.com/chapter/10.1007/978-3-030-11039-0_5',
                'authors' => 'Zaharah Allah Bukhsh, Marten van Sinderen, Klaas Sikkel and Dick Quartel',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '43',
            ],
            [
                'id' => 44,
                'title' => 'Integrating IoT-Driven Events into Business Processes',
                'year' => 2023,
                'journal' => 'Sensors',
                'url' => 'https://link.springer.com/chapter/10.1007/978-3-031-34674-3_11',
                'authors' => 'Kirikkayis, Yusuf and Gallik, Florian and Seiger, Ronny and Reichert, Manfred',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '44',
            ],
            [
                'id' => 45,
                'title' => 'Integrating Quantum Computing into WorkFlowElements Modeling and Execution',
                'year' => 2020,
                'journal' => 'IEEE Access',
                'url' => 'https://ieeexplore.ieee.org/abstract/document/9302814/',
                'authors' => 'Weder, Benjamin and Breitenbücher, Uwe and Leymann, Frank and Wild, Karoline',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '45',
            ],
            [
                'id' => 46,
                'title' => 'IoT-fog-cloud based architecture for smart systems: Prototypes of autism and COVID-19 monitoring systems',
                'year' => 2021,
                'journal' => 'Journal of Ambient Intelligence and Humanized Computing',
                'url' => 'https://onlinelibrary.wiley.com/doi/abs/10.1002/spe.2924',
                'authors' => 'Kallel, Ameni and Rekik, Molka and Khemakhem, Mahdi',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '46',
            ],
            [
                'id' => 47,
                'title' => 'IoTDM4BPMN: An IoT-Enhanced Decision Making Framework for BPMN 2.0',
                'year' => 2022,
                'journal' => 'IEEE Access',
                'url' => 'https://ieeexplore.ieee.org/abstract/document/9860216/',
                'authors' => 'Kirikkayis, Yusuf and Gallik, Florian and Reichert, Manfred',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => 23,
                'type' => 'Conference',
                'short_title' => '47',
            ],
            [
                'id' => 48,
                'title' => 'Modeling and Execution of Blockchain-aware Business Processes',
                'year' => 2019,
                'journal' => 'Information Systems',
                'url' => 'https://link.springer.com/article/10.1007/s00450-019-00399-5',
                'authors' => 'Ghareeb Falazi, Michael Hahn, Uwe Breitenbücher, Frank Leymann',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '48',
            ],
            [
                'id' => 49,
                'title' => 'Modeling Boundary-Spanning Business Processes in Industry 4.0 Incorporating Risk-Based Design',
                'year' => 2022,
                'journal' => 'Journal of Industrial Information Integration',
                'url' => 'https://link.springer.com/chapter/10.1007/978-3-030-95354-6_9',
                'authors' => 'Vítor Ribeiro, João Barata and Paulo Rupino da Cunha',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => 2,
                'type' => 'Conference',
                'short_title' => '49',
            ],
            [
                'id' => 50,
                'title' => 'Modeling inter-organizational business process governance in the age of collaborative networks',
                'year' => 2024,
                'journal' => 'Business Process Management Journal',
                'url' => 'https://link.springer.com/article/10.1007/s12525-024-00730-2',
                'authors' => 'Vítor Ribeiro, João Barata, Paulo Rupino da Cunha',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '50',
            ],
            [
                'id' => 51,
                'title' => 'Modeling the Integration of Machine Learning into Business Processes with BPMN',
                'year' => 2023,
                'journal' => 'IEEE Access',
                'url' => 'https://link.springer.com/chapter/10.1007/978-981-99-3236-8_76',
                'authors' => 'Marius Take, Christoph Becker, Sascha Alpers, Andreas Oberweis',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '51',
            ],
            [
                'id' => 52,
                'title' => 'Modeling, Executing and Monitoring IoT-Aware Processes with BPM Technology',
                'year' => 2022,
                'journal' => 'Sensors',
                'url' => 'https://ieeexplore.ieee.org/abstract/document/9860104/',
                'authors' => 'Gallik, Florian and Kirikkayis, Yusuf and Reichert, Manfred',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => 23,
                'type' => 'Conference',
                'short_title' => '52',
            ],
            [
                'id' => 53,
                'title' => 'Modelling context awareness in Internet of Things with business process model and notation 2.0 extensions',
                'year' => 2021,
                'journal' => 'Journal of Ambient Intelligence and Humanized Computing',
                'url' => 'https://www.inderscienceonline.com/doi/abs/10.1504/IJAIP.2021.119025',
                'authors' => 'Tayur, Varun M. and Suchithra, R.',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '53',
            ],
            [
                'id' => 54,
                'title' => 'Modelling technical compromises in electronics manufacturing with BPMN+TD',
                'year' => 2021,
                'journal' => 'Journal of Manufacturing Systems',
                'url' => 'https://www.sciencedirect.com/science/article/pii/S2405896321008582',
                'authors' => 'Quang Huan Dong, Birgit Vogel-Heuser',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '54',
            ],
            [
                'id' => 55,
                'title' => 'On the Interplay Between BPMN Collaborations and the Physical Environment',
                'year' => 2024,
                'journal' => 'Information Systems',
                'url' => 'https://link.springer.com/chapter/10.1007/978-3-031-70396-6_6',
                'authors' => 'Flavio Corradini, Jessica Piccioni, Barbara Re, Lorenzo Rossi, Francesco Tiezzi',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '55',
            ],
            [
                'id' => 56,
                'title' => 'Privacy-enhanced BPMN: enabling data privacy analysis in business processes models',
                'year' => 2019,
                'journal' => 'Information and Software Technology',
                'url' => 'https://link.springer.com/article/10.1007/s10270-019-00718-z',
                'authors' => 'Pille Pullonen, Jake Tom, Raimundas Matulevičius, Aivo Toots',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '56',
            ],
            [
                'id' => 57,
                'title' => 'Process business modeling of emerging security threats with BPMN extension',
                'year' => 2021,
                'journal' => 'Computers & Security',
                'url' => 'https://aisel.aisnet.org/wisp2021/8/',
                'authors' => 'Tomasz Krym, Lukasz Chomątek, Aneta Poniszewska-Marańda',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => 32,
                'type' => 'Conference',
                'short_title' => '57',
            ],
            [
                'id' => 58,
                'title' => 'Process-Based Quality Management in Care: Adding a Quality Perspective to Pathway Modelling',
                'year' => 2019,
                'journal' => 'Health Informatics Journal',
                'url' => 'https://link.springer.com/chapter/10.1007/978-3-030-33246-4_25',
                'authors' => 'Richter, Peggy and Schlieter, Hannes',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '58',
            ],
            [
                'id' => 59,
                'title' => 'Process-Oriented Requirements Definition and Analysis of Software Components in Critical Systems',
                'year' => 2023,
                'journal' => 'Journal of Systems and Software',
                'url' => 'https://www.mdpi.com/2073-431X/12/9/184',
                'authors' => 'Benedetto Intrigila, Giuseppe Della Penna, Andrea D’Ambrogio, Dario Campagna, Malina Grigore',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '59',
            ],
            [
                'id' => 60,
                'title' => 'Production-Aware Analysis of Multi-disciplinary Systems Engineering Processes',
                'year' => 2019,
                'journal' => 'Journal of Industrial Information Integration',
                'url' => 'https://pdfs.semanticscholar.org/8ed0/ed60b3a19b710888e2914a669ea7c4dd4fd5.pdf',
                'authors' => 'Kathrein, Lukas and Luder, Arndt and Meixner, Kristof and Winkler, Dietmar and Biffl, Stefan',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '60',
            ],
            [
                'id' => 61,
                'title' => 'Proposal of BPMN extensions for modelling manufacturing processes',
                'year' => 2019,
                'journal' => 'Journal of Industrial Information Integration',
                'url' => 'https://ieeexplore.ieee.org/abstract/document/8727651/',
                'authors' => 'Abouzid, Ihsane and Saidi, Rajaa',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '61',
            ],
            [
                'id' => 62,
                'title' => 'QuantME4VQA: Modeling and Executing Variational Quantum Algorithms Using WorkFlowElementss',
                'year' => 2023,
                'journal' => 'IEEE Access',
                'url' => 'https://www.scitepress.org/Papers/2023/119975/119975.pdf',
                'authors' => 'Martin Beisel, Johanna Barzen, Marvin Bechtold, Frank Leymann, Felix Truger, Benjamin Weder',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '62',
            ],
            [
                'id' => 63,
                'title' => 'R-BPMN for abstract modeling of business process patterns',
                'year' => 2021,
                'journal' => 'Journal of Systems and Software',
                'url' => 'https://www.emerald.com/insight/content/doi/10.1108/bpmj-08-2020-0371/full/html',
                'authors' => 'Dae-Kyoo Kim, Yeasun K. Chung',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => 44,
                'type' => 'Journal',
                'short_title' => '63',
            ],
            [
                'id' => 64,
                'title' => 'RBPMN - The Power of Roles for Business Process Modeling with BPMN',
                'year' => 2022,
                'journal' => 'Business Process Management Journal',
                'url' => 'https://link.springer.com/chapter/10.1007/978-3-031-07475-2_3',
                'authors' => 'Tarek Skouti, Frank J. Furrer, Susanne Strahringe',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '64',
            ],
            [
                'id' => 65,
                'title' => 'RBPMN A ROLE-BASED BPMN FOR INTEGRATING STRUCTURE AND BEHAVIOR MODELS',
                'year' => 2021,
                'journal' => 'Journal of Systems and Software',
                'url' => 'https://tud.qucosa.de/id/qucosa:73315',
                'authors' => 'Von Tarek Skouti',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => 63,
                'type' => 'Conference',
                'short_title' => '65',
            ],
            [
                'id' => 66,
                'title' => 'Reliability of IoT-Aware BPMN Healthcare Processes',
                'year' => 2019,
                'journal' => 'Health Informatics Journal',
                'url' => 'https://www.igi-global.com/chapter/reliability-of-iot-aware-bpmn-healthcare-processes/235345',
                'authors' => 'Domingos, Dulce and Respício, Ana and Martinho, Ricardo',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Book Chapter',
                'short_title' => '66',
            ],
            [
                'id' => 67,
                'title' => 'Resilient Business Process Modeling and Execution using BPMN and Microservices',
                'year' => 2021,
                'journal' => 'Journal of Systems and Software',
                'url' => 'https://link.springer.com/chapter/10.1007/978-3-030-67445-8_8',
                'authors' => 'Nordemann, Frank and Tonjes, Ralf and Pulvermuller, Elke and Tapken, Heiko',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '67',
            ],
            [
                'id' => 68,
                'title' => 'Resource provisioning strategies for BPMN processes: Specification and analysis using Maude',
                'year' => 2021,
                'journal' => 'Software and Systems Modeling',
                'url' => 'https://www.sciencedirect.com/science/article/pii/S2352220821000742',
                'authors' => 'Francisco Durán and Camilo Rocha and Gwen Salaün',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '68',
            ],
            [
                'id' => 69,
                'title' => 'Risk-oriented design approach for forensic-ready software systems',
                'year' => 2021,
                'journal' => 'Information and Software Technology',
                'url' => 'https://dl.acm.org/doi/abs/10.1145/3465481.3470052',
                'authors' => 'Lukas Daubner, Raimundas Matulevičius',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => 25,
                'type' => 'Conference',
                'short_title' => '69',
            ],
            [
                'id' => 70,
                'title' => 'riskaBPMN - a BPMN extension for risk assessment',
                'year' => 2021,
                'journal' => 'Journal of Systems and Software',
                'url' => 'https://www.sciencedirect.com/science/article/pii/S1877050921003756',
                'authors' => 'Pedro Cardoso and Ana Respício and Dulce Domingos',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => 70,
                'type' => 'Journal',
                'short_title' => '70',
            ],
            [
                'id' => 71,
                'title' => 'Security Requirements Engineering Framework with BPMN 2.0.2 Extension Model for Development of Information Systems',
                'year' => 2020,
                'journal' => 'Information Systems',
                'url' => 'https://www.mdpi.com/2076-3417/10/14/4981',
                'authors' => 'Zareen, Saima and Akram, Adeel and Khan, Shoab Ahmad',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '71',
            ],
            [
                'id' => 72,
                'title' => 'Service Modeling and Architecting for Self-Adaptive IoT-Based Systems',
                'year' => 2022,
                'journal' => 'Journal of Systems and Software',
                'url' => 'https://ceur-ws.org/Vol-3176/paper6.pdf',
                'authors' => 'Merabet, Fatima Zohra and Benmerzoug, Djamel',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '72',
            ],
            [
                'id' => 73,
                'title' => 'The Effect of Risk Representation Using Colors and Symbols in Business Process Models on Operational Risk Management Performance',
                'year' => 2021,
                'journal' => 'Business Process Management Journal',
                'url' => 'https://eprints.qut.edu.au/214314',
                'authors' => 'Kummer, Tyge-F. and Mendling, Jan',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '73',
            ],
            [
                'id' => 74,
                'title' => 'TimeAwareBPMN-js: An editor and temporal verification tool for Time-Aware BPMN processes',
                'year' => 2022,
                'journal' => 'Software and Systems Modeling',
                'url' => 'https://www.sciencedirect.com/science/article/pii/S2352711021001734',
                'authors' => 'Mario Ocampo-Pineda, Roberto Posenato, Francesca Zerbato',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '74',
            ],
            [
                'id' => 75,
                'title' => 'TM4BPPMN: Recasting BPMN to Low-Level of Abstraction',
                'year' => 2022,
                'journal' => 'Journal of Systems and Software',
                'url' => 'https://www.academia.edu/download/98569953/asmsj.pdf',
                'authors' => 'Zineb Lamghari',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Journal',
                'short_title' => '75',
            ],
            [
                'id' => 76,
                'title' => 'Towards a Comprehensive BPMN Extension for Modeling IoT-Aware Processes in Business Process Models',
                'year' => 2022,
                'journal' => 'IEEE Access',
                'url' => 'https://link.springer.com/chapter/10.1007/978-3-031-05760-1_47',
                'authors' => 'Kirikkayis, Yusuf and Gallik, Florian and Reichert, Manfred',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => 23,
                'type' => 'Conference',
                'short_title' => '76',
            ],
            [
                'id' => 77,
                'title' => 'Towards a Continuous Temporal Improvement Approach for Real-Time Business Processes',
                'year' => 2024,
                'journal' => 'Journal of Systems and Software',
                'url' => 'https://search.ebscohost.com/login.aspx?direct=true&profile=ehost&scope=site&authtype=crawler&jrnl=2158107X&AN=175401696&h=fRTXcmKXDrnftgTQ%2Fnc58iTVlbql7lLUFfGbgs1H7L%2BSCJZPLjhZMHr41iG6v0cRxRX0TaF6chgJ53YBuNvEew%3D%3D&crl=c',
                'authors' => 'Asma Ouarhim, Karim Baïna, Brahim Elbhiri',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => 5,
                'type' => 'Journal',
                'short_title' => '77',
            ],
            [
                'id' => 78,
                'title' => 'TOWARDS A META-MODELING APPROACH FOR AN IORT-AWARE BUSINESS PROCESS',
                'year' => 2022,
                'journal' => 'Journal of Systems and Software',
                'url' => 'https://www.scs-europe.net/dlib/2022/ecms2022acceptedpapers/0029_bpmi_ecms2022_0050.pdf',
                'authors' => 'Fattouch, Najla and Lahmar, Imen Ben and Boukadi, Khouloud',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '78',
            ],
            [
                'id' => 79,
                'title' => 'Tracking Interoperability and Data Quality: A Methodology with BPMN 2.0 Extensions and Performance Evaluation',
                'year' => 2024,
                'journal' => 'IEEE Access',
                'url' => 'https://www.mdpi.com/2673-3951/5/3/42',
                'authors' => 'Xabier Heguy, Said Tazi, Gregory Zacharewicz, Yves Ducq',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => 10,
                'type' => 'Journal',
                'short_title' => '79',
            ],
            [
                'id' => 80,
                'title' => 'Zooming in for Clarity: Towards low-code modeling for Activity Data FlowElements',
                'year' => 2023,
                'journal' => 'Journal of Systems and Software',
                'url' => 'https://link.springer.com/chapter/10.1007/978-3-031-41623-1_16',
                'authors' => 'Nour Eldin, Ali and Baudot, Jonathan and Gaaloul, Walid',
                'image' => null,
                'approved' => 1,
                'user_id' => 1,
                'notes' => null,
                'created_at' => null,
                'updated_at' => null,
                'publications_id' => null,
                'type' => 'Conference',
                'short_title' => '80',
            ],
        ]);
    }
}
