-- MySQL Script generated by MySQL Workbench
-- Qui 03 Nov 2016 13:22:38 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mrrt
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mrrt` ;

-- -----------------------------------------------------
-- Schema mrrt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mrrt` DEFAULT CHARACTER SET utf8 ;
USE `mrrt` ;

-- -----------------------------------------------------
-- Table `mrrt`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mrrt`.`users` ;

CREATE TABLE IF NOT EXISTS `mrrt`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `social_id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `provider` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `rule` ENUM('user', 'team', 'admin') NOT NULL DEFAULT 'user',
  `remember_token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `affiliation` VARCHAR(255) NULL,
  `personal_url` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mrrt`.`publications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mrrt`.`publications` ;

CREATE TABLE IF NOT EXISTS `mrrt`.`publications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `year` INT NULL,
  `url` VARCHAR(255) NULL,
  `journal` TEXT NULL,
  `authors` TEXT NULL,
  `image` VARCHAR(255) NULL,
  `approved` TINYINT(1) NULL,
  `user_id` INT NULL,
  `notes` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `publications_id` INT NULL,
  `type` ENUM('Book Chapter', 'Journal', 'Conference') NULL,
  `short_title` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_publications_users_idx` (`user_id` ASC),
  INDEX `fk_publications_publications1_idx` (`publications_id` ASC),
  CONSTRAINT `fk_publications_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `mrrt`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_publications_publications1`
    FOREIGN KEY (`publications_id`)
    REFERENCES `mrrt`.`publications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mrrt`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mrrt`.`categories` ;

CREATE TABLE IF NOT EXISTS `mrrt`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(400) NOT NULL,
  `description` TEXT NULL,
  `type` ENUM('image', 'text', 'tag') NOT NULL,
  `total_allowed` INT NOT NULL DEFAULT 0,
  `image_category` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mrrt`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mrrt`.`images` ;

CREATE TABLE IF NOT EXISTS `mrrt`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(255) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `category_id` INT NOT NULL,
  `publication_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_images_galery1_idx` (`category_id` ASC),
  INDEX `fk_images_publications1_idx` (`publication_id` ASC),
  CONSTRAINT `fk_images_galery1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mrrt`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_images_publications1`
    FOREIGN KEY (`publication_id`)
    REFERENCES `mrrt`.`publications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'galery_id';


-- -----------------------------------------------------
-- Table `mrrt`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mrrt`.`tags` ;

CREATE TABLE IF NOT EXISTS `mrrt`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(400) NOT NULL,
  `description` TEXT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tags_categories1_idx` (`category_id` ASC),
  CONSTRAINT `fk_tags_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mrrt`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mrrt`.`publications_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mrrt`.`publications_tags` ;

CREATE TABLE IF NOT EXISTS `mrrt`.`publications_tags` (
  `publication_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`publication_id`, `tag_id`),
  INDEX `fk_publications_has_tags_tags1_idx` (`tag_id` ASC),
  INDEX `fk_publications_has_tags_publications1_idx` (`publication_id` ASC),
  CONSTRAINT `fk_publications_has_tags_publications1`
    FOREIGN KEY (`publication_id`)
    REFERENCES `mrrt`.`publications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_publications_has_tags_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `mrrt`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mrrt`.`text_fields`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mrrt`.`text_fields` ;

CREATE TABLE IF NOT EXISTS `mrrt`.`text_fields` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `publication_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `images_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_extratext_publications1_idx` (`publication_id` ASC),
  INDEX `fk_extra_fields_categories1_idx` (`category_id` ASC),
  INDEX `fk_text_fields_images1_idx` (`images_id` ASC),
  CONSTRAINT `fk_extratext_publications1`
    FOREIGN KEY (`publication_id`)
    REFERENCES `mrrt`.`publications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_extra_fields_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mrrt`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_text_fields_images1`
    FOREIGN KEY (`images_id`)
    REFERENCES `mrrt`.`images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mrrt`.`quality_questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mrrt`.`quality_questions` ;

CREATE TABLE IF NOT EXISTS `mrrt`.`quality_questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` TEXT NOT NULL,
  `intermediary_value` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mrrt`.`publications_quality_questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mrrt`.`publications_quality_questions` ;

CREATE TABLE IF NOT EXISTS `mrrt`.`publications_quality_questions` (
  `quality_question_id` INT NOT NULL,
  `publication_id` INT NOT NULL,
  `value` FLOAT NOT NULL,
  PRIMARY KEY (`quality_question_id`, `publication_id`),
  INDEX `fk_quality_question_has_publications_publications6_idx` (`publication_id` ASC),
  INDEX `fk_quality_question_has_publications_quality_question6_idx` (`quality_question_id` ASC),
  CONSTRAINT `fk_quality_question_has_publications_quality_question6`
    FOREIGN KEY (`quality_question_id`)
    REFERENCES `mrrt`.`quality_questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quality_question_has_publications_publications6`
    FOREIGN KEY (`publication_id`)
    REFERENCES `mrrt`.`publications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mrrt`.`images_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mrrt`.`images_tags` ;

CREATE TABLE IF NOT EXISTS `mrrt`.`images_tags` (
  `images_id` INT NOT NULL,
  `tags_id` INT NOT NULL,
  PRIMARY KEY (`images_id`, `tags_id`),
  INDEX `fk_images_has_tags_tags1_idx` (`tags_id` ASC),
  INDEX `fk_images_has_tags_images1_idx` (`images_id` ASC),
  CONSTRAINT `fk_images_has_tags_images1`
    FOREIGN KEY (`images_id`)
    REFERENCES `mrrt`.`images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_images_has_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `mrrt`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mrrt`.`constructs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mrrt`.`constructs` ;

CREATE TABLE IF NOT EXISTS `mrrt`.`constructs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `concept` VARCHAR(255) NOT NULL,
  `form` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `type` ENUM('entity', 'relantioship') NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `publications_id` INT NOT NULL,
  `example_image` VARCHAR(255) NULL,
  `priorization` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_constructs_publications1_idx` (`publications_id` ASC),
  UNIQUE INDEX `example_image_UNIQUE` (`example_image` ASC),
  CONSTRAINT `fk_constructs_publications1`
    FOREIGN KEY (`publications_id`)
    REFERENCES `mrrt`.`publications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mrrt`.`classifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mrrt`.`classifications` ;

CREATE TABLE IF NOT EXISTS `mrrt`.`classifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(400) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mrrt`.`representation_forms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mrrt`.`representation_forms` ;

CREATE TABLE IF NOT EXISTS `mrrt`.`representation_forms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NOT NULL,
  `classification_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_representation_forms_finalities1_idx` (`classification_id` ASC),
  CONSTRAINT `fk_representation_forms_finalities1`
    FOREIGN KEY (`classification_id`)
    REFERENCES `mrrt`.`classifications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mrrt`.`constructs_representation_forms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mrrt`.`constructs_representation_forms` ;

CREATE TABLE IF NOT EXISTS `mrrt`.`constructs_representation_forms` (
  `constructs_id` INT NOT NULL,
  `representation_forms_id` INT NOT NULL,
  PRIMARY KEY (`constructs_id`, `representation_forms_id`),
  INDEX `fk_constructs_has_representation_forms_representation_forms_idx` (`representation_forms_id` ASC),
  INDEX `fk_constructs_has_representation_forms_constructs1_idx` (`constructs_id` ASC),
  CONSTRAINT `fk_constructs_has_representation_forms_constructs1`
    FOREIGN KEY (`constructs_id`)
    REFERENCES `mrrt`.`constructs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_constructs_has_representation_forms_representation_forms1`
    FOREIGN KEY (`representation_forms_id`)
    REFERENCES `mrrt`.`representation_forms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mrrt`.`conflict_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mrrt`.`conflict_categories` ;

CREATE TABLE IF NOT EXISTS `mrrt`.`conflict_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(400) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mrrt`.`conflicts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mrrt`.`conflicts` ;

CREATE TABLE IF NOT EXISTS `mrrt`.`conflicts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NOT NULL,
  `conflict_category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_conflicts_conflict_category1_idx` (`conflict_category_id` ASC),
  CONSTRAINT `fk_conflicts_conflict_category1`
    FOREIGN KEY (`conflict_category_id`)
    REFERENCES `mrrt`.`conflict_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mrrt`.`conflicts_constructs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mrrt`.`conflicts_constructs` ;

CREATE TABLE IF NOT EXISTS `mrrt`.`conflicts_constructs` (
  `conflict_id` INT NOT NULL,
  `constructs_id` INT NOT NULL,
  PRIMARY KEY (`conflict_id`, `constructs_id`),
  INDEX `fk_conflict_has_constructs_constructs1_idx` (`constructs_id` ASC),
  INDEX `fk_conflict_has_constructs_conflict1_idx` (`conflict_id` ASC),
  CONSTRAINT `fk_conflict_has_constructs_conflict1`
    FOREIGN KEY (`conflict_id`)
    REFERENCES `mrrt`.`conflicts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conflict_has_constructs_constructs1`
    FOREIGN KEY (`constructs_id`)
    REFERENCES `mrrt`.`constructs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mrrt`.`descendants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mrrt`.`descendants` ;

CREATE TABLE IF NOT EXISTS `mrrt`.`descendants` (
  `descendant_id` INT NOT NULL,
  `root_id` INT NOT NULL,
  PRIMARY KEY (`descendant_id`, `root_id`),
  INDEX `fk_publications_has_publications_publications2_idx` (`root_id` ASC),
  INDEX `fk_publications_has_publications_publications1_idx` (`descendant_id` ASC),
  CONSTRAINT `fk_publications_has_publications_publications1`
    FOREIGN KEY (`descendant_id`)
    REFERENCES `mrrt`.`publications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_publications_has_publications_publications2`
    FOREIGN KEY (`root_id`)
    REFERENCES `mrrt`.`publications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
